name: Discord Webhook Notify
author: rjstone
description: >
  Send notifications to Discord using a webhook.
  Works with all execution environments including windows, macos, and linux.
inputs:
  webhookUrl:
    description: >
      Discord webhook URL. Should be stored in a repo secret (Settings>Security>Secrets) and inserted
      in the action call as a context expression.
    required: true
  flags:
    description: >
      A whitespace-separated list of MessageFlags. The only one supported currently is SuppressNotifications.
    required: false
    default: ""
  username:
    description: >
      Username to display in discord. Must be 2-32 chars long and can't contain: @, #, :, ```, discord
      Also can't be "here" or "everyone", for obvious reasons.
    required: false
    default: "Notification (Github Actions)"
  avatarUrl:
    description: >
      URL to png of discord avatar to use. Default is the GitHub monochrome mark cat logo.
      May not work depending on Discord policy.
    required: false
    default: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  text:
    description: Text to be sent as normal text above the embed. Defaults to empty string.
    required: false
  severity:
    description: >
      Severity level - info, warn, error, or none. Using "none" will cause no embed to be added.
      Using any other value will cause an embed with a set of matching defaults to be added.
    required: false
    default: none
  color:
    description: "Notification embed color in the form #rrggbb (hex). Default determined by severity."
    required: false
  title:
    description: Title for the embed. Defaults to severity long terminology.
    required: false
  description:
    description: Embed notification message. Default provides some minimal github.context workflow info.
    required: false
  details:
    description: >
      Additional text after the description in case you want to retain the default embed description.
      Defaults to empty string.
    required: false
  linkUrl:
    description: >
      URL to link the title to. If not specified, title will not be a link.
      If specified without a title, the link will be ignored.
    required: false
  fields:
    description: >
      A JSON array of field objects to add to the embed. Each object should have "name", "value",
      and optional "inline" boolean properties. Example:
      `[{"name":"Field1","value":"Some value","inline":true},{"name":"Field2","value":"Another value"}]`
    required: false
  footer:
    description: Footer for the embed. Defaults to long terminology severity.
    required: false
  processingOptions:
    description: >
      (EXPERIMENTAL) Set to "percentDecode" if you want some inputs that are
      often multi-line strings to be run through "percent decoding" using
      decodeURIComponent(). This can be useful in cases where the output from
      another action should contain newlines, but won't be preserved by the
      Workflow system if it does.
    required: false
    default: ""
  holddownTime:
    description: >
      The minimum amount of time in miliseconds between successive notifications to avoid triggering Discord's
      rate limiting.
    required: false
    default: "3000"
  lockfileDir:
    description: >
      The directory where the lockfile used for saving last run time is stored.
    required: false
    default: "."


runs:
  using: "node20"
  main: "dist/index.js"
branding:
  color: orange
  icon: alert-triangle