name: Discord Webhook Notify
author: rjstone
description: >
  Send notifications to Discord using a webhook.
  Works with all execution environments including windows, macos, and linux.
inputs:
  webhookUrl:
    description: >
      Discord webhook URL. Should be stored in a repo secret (Settings>Security>Secrets) and inserted
      in the action call as a context expression.
    required: true
  holddownTime:
    description: >
      The minimum amount of time in miliseconds between successive notifications to avoid triggering Discord's
      rate limiting.
    required: false
    default: "3000"
  username:
    description: Username to display in discord.
    required: false
    default: "Notification (Github Actions)"
  avatarUrl:
    description: >
      URL to png of discord avatar to use. Default is the GitHub monochrome mark cat logo.
      May not work depending on Discord policy.
    required: false
    default: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  text:
    description: Text to be sent as normal text above the embed. Defaults to empty string.
    required: false
  severity:
    description: Severity level - info, warn, or error.
    required: false
    default: info
  color:
    description: "Notification embed color in the form #rrggbb (hex). Default determined by severity."
    required: false
  title:
    description: Title for the embed. Defaults to severity long terminology.
    required: false
  description:
    description: Embed notification message. Default provides some minimal github.context workflow info.
    required: false
  details:
    description: >
      Additional text after the description in case you want to retain the default embed description.
      Defaults to empty string.
    required: false
  footer:
    description: Footer for the embed. Defaults to long terminology severity.
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  color: orange
  icon: alert-triangle