name: Continuous Integration
permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main
      - v2
    paths:
      - .github/workflows/ci.yml
      - __fixtures__/
      - __tests__/
      - src/
      - .node-version
      - .prettierrc
      - .yaml-lint.yml
      - test.env
      - jest.config.js
      - package.json
      - package-lock.json
      - eslint.config.mjs
      - action.yml
  pull_request:
    branches:
      - main
      - v2

env:
  BADGES_BRANCH: 'badges'
  REF_NAME: ${{ github.ref_name }}
  REF_TYPE: ${{ github.ref_type }}
  BRANCH_NAME: ${{ ( github.ref_type == 'branch' && github.ref_name ) || '' }}
  TAG_NAME: ${{ ( github.ref_type == 'tag' && github.ref_name ) || '' }}

jobs:
  test-javascript:
    name: Unit Tests (jest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - run: echo "build_status_message=FAIL" >> $GITHUB_ENV
      - run: echo "build_status_color=9e1010" >> $GITHUB_ENV

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-test-ci
        run: npm run test-ci

      - if: success()
        run: echo "build_status_message=PASS" >> $GITHUB_ENV
      - if: success()
        run: echo "build_status_color=209215" >> $GITHUB_ENV

      - name: ⚙️ Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        with:
          branches: main,v2
          target-branch: ${{ env.BADGES_BRANCH }}
          badges-icon: jest
          output-folder: ./.badges_${{ env.BRANCH_NAME }}
          badges-labels-prefix: '${{ env.BADGES_BRANCH }} coverage:'

      - name: Ci Status Badge
        if: ${{ success() && env.BRANCH_NAME }}
        uses: action-badges/core@0.3.1
        with:
          label: "CI Status (${{ env.BRANCH_NAME }})"
          label-color: gray
          message: 'PASS'
          message-color: 209215
          file-name: ./.badges_${{ env.BRANCH_NAME }}/ci_status.svg
          badge-branch: ${{ env.BADGES_BRANCH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          style: flat-square

  test-execution-of-src:
    name: src Smoke Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Action
        id: test-action
        uses: ./
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: "CI Test"
          severity: "info"
          flags: SuppressNotifications

      - name: Print Output
        id: output
        run: echo "OUTPUT\n${{ steps.test-action.outputs }}"
