name: Continuous Integration
permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main
      - v2
    paths:
      - .github/workflows/ci.yml
      - __fixtures__/
      - __tests__/
      - src/
      - .node-version
      - .prettierrc
      - .yaml-lint.yml
      - test.env
      - jest.config.js
      - package.json
      - package-lock.json
      - eslint.config.mjs
      - action.yml
  pull_request:
    branches:
      - main
      - v2

env:
  REF_NAME: ${{ github.ref_name }}
  REF_TYPE: ${{ github.ref_type }}
  BRANCH_NAME: ${{ ( github.ref_type == 'branch' && github.ref_name ) || '' }}
  TAG_NAME: ${{ ( github.ref_type == 'tag' && github.ref_name ) || '' }}

jobs:
  test-javascript:
    name: Unit Tests (jest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run test

      - name: Coverage Badge
        id: npm-coverage
        run: npm run coverage

      - name: Badge - CI Success
        if: ${{ success() && env.BRANCH_NAME }}
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          name: ci_status_${{ env.BRANCH_NAME }}
          label: "CI Status ${{ env.BRANCH_NAME }}"
          status: PASS
          color: 00cc00
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Badge - CI Failure
        if: ${{ ( ! success() ) && env.BRANCH_NAME }}
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          name: ci_status_${{ env.BRANCH_NAME }}
          label: "CI Status ${{ env.BRANCH_NAME }}"
          status: FAIL
          color: aa0000
          github_token: ${{ secrets.GITHUB_TOKEN }}

  test-execution-of-src:
    name: src Smoke Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Action
        id: test-action
        uses: ./
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: "CI Test"
          severity: "info"
          flags: SuppressNotifications

      - name: Print Output
        id: output
        run: echo "OUTPUT\n${{ steps.test-action.outputs }}"
