name: Simple Use Case Tests
permnissions: read-all
on:
  push:
    branches:
      - main
jobs:
  windows_test:
    runs-on: windows-latest
    name: Windows Test Job
    steps:
    - name: Windows Test No Embed
      uses: rjstone/discord-webhook-notify@main
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        username: Windows Bot
        text: This is some text. **Workflow:** ${{ github.workflow }}
    - name: Windows Test Default Embed
      uses: rjstone/discord-webhook-notify@main
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        username: Windows Bot
        text: This is a generic warning. **Workflow:** ${{ github.workflow }}
        severity: warn
  linux_test:
    runs-on: ubuntu-latest
    name: Linux Test Job
    steps:
    - name: Linux Test Custom
      uses: rjstone/discord-webhook-notify@main
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        username: Linux Bot
        text: This is some generic info you might want to see.
        severity: info
        details: 'Custom details: Somebody set up us the bomb.'
  macos_test:
    runs-on: macos-latest
    name: MacOS Test Job
    steps:
    - name: MacOS Test Custom
      uses: rjstone/discord-webhook-notify@main
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        username: MacOS X Bot
        text: Mac Bot seems to be having Problems or something.
        severity: error
        color: '#ff00aa'
        description: This is a custom description.
        footer: This is a footer.