name: Simple Use Case Tests
on:
  push:
    branches:
      - main
jobs:
  windows_test:
    runs-on: windows-latest
    name: Windows Test Job
    steps:
    - name: Windows Test Custom
      uses: rjstone/discord-webhook-notify@main
      with:
        severity: info
        username: CustomUsername
        color: '#ff00aa'
        avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
        description: This is a custom description.
        details: 'Custom details: Somebody set up us the bomb.'
        footer: This is a footer.
        text: This is where text goes.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Windows Test Failure
      uses: rjstone/discord-webhook-notify@main
      if: failure()
      with:
        severity: error
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  linux_test:
    runs-on: ubuntu-latest
    name: Linux Test Job
    steps:
    - name: Linux Test Custom
      uses: rjstone/discord-webhook-notify@main
      with:
        severity: info
        username: CustomUsername
        color: '#ff00aa'
        avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
        description: This is a custom description.
        details: 'Custom details: Somebody set up us the bomb.'
        footer: This is a footer.
        text: This is where text goes.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Failure
      uses: rjstone/discord-webhook-notify@main
      if: failure()
      with:
        severity: error
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  macos_test:
    runs-on: macos-latest
    name: MacOS Test Job
    steps:
    - name: MacOS Test Custom
      uses: rjstone/discord-webhook-notify@main
      with:
        severity: info
        username: CustomUsername
        color: '#ff00aa'
        avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
        description: This is a custom description.
        details: 'Custom details: Somebody set up us the bomb.'
        footer: This is a footer.
        text: This is where text goes.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: MacOS Test Failure
      uses: rjstone/discord-webhook-notify@main
      if: failure()
      with:
        severity: error
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}